

CREATE DATABASE IF NOT EXISTS mvc;  
CREATE USER 'mvc'@'localhost' IDENTIFIED BY 'mvc';
GRANT SELECT,INSERT,UPDATE,ALTER,DELETE,CREATE,DROP,CREATE TEMPORARY TABLES,CREATE VIEW,SHOW VIEW ON mvc.* TO 'mvc'@'localhost';
FLUSH PRIVILEGES;